# Generated by Django 6.0 on 2025-12-14 22:19

import django.db.models.deletion
import resenhas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_livro', models.CharField(max_length=1000, validators=[resenhas.models.validate_max_words_50])),
                ('autor_livro', models.CharField(max_length=1000, validators=[resenhas.models.validate_max_words_50])),
                ('url_imagem', models.URLField(blank=True, null=True)),
                ('texto_resenha', models.TextField(validators=[resenhas.models.validate_max_words_500])),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('curtidas', models.ManyToManyField(blank=True, related_name='resenhas_curtidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenhas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('curtidas', models.ManyToManyField(blank=True, related_name='comentarios_curtidos', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='resenhas.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resenha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='resenhas.resenha')),
            ],
        ),
    ]
