# Generated by Django 6.0 on 2025-12-15 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenhas', '0002_mensagem_notificacao_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['data']},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-data']},
        ),
        migrations.RenameField(
            model_name='mensagem',
            old_name='data_envio',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='mensagem',
            old_name='conteudo',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='notificacao',
            old_name='data_criacao',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='lida',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='foto',
        ),
        migrations.AddField(
            model_name='perfil',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://ui-avatars.com/api/?background=random', null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgs_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgs_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('curtida', 'Curtida'), ('comentario', 'Comentário'), ('mensagem', 'Mensagem')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='hobbies',
            field=models.TextField(blank=True, default=''),
        ),
    ]
