# Generated by Django 6.0 on 2025-12-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenhas', '0003_alter_mensagem_options_alter_notificacao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
